apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-db-depl
spec:
  selector:
    matchLabels:
      app: bookings-db
  template:
    metadata:
      labels:
        app: bookings-db
    spec:
      containers:
        - name: bookings-db
          image: mongo
          ports:
            - containerPort: 27017
          

---
apiVersion: v1
kind: Service
metadata:
  name: bookings-db-srv
spec:
  selector:
    app: bookings-db
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
