apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: event-management
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/**/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: event-management/auth
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: src
    - image: event-management/bookings
      context: bookings-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: src
    - image: event-management/events
      context: events-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: src
    - image: event-management/expiration
      context: expiration-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: src
    - image: event-management/payments
      context: payments-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: src
    - image: event-management/orders
      context: orders-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: src
    - image: event-management/streaming
      context: streaming-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: src
