apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-depl
spec:
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
        - name: streaming
          image: event-management/streaming
          env:
            - name: MONGO_URI
              value: mongodb://streaming-db-srv:27019/Streaming
            - name: EVENTBUS_URI
              value: amqp://rabbitmq-srv:5672

---
apiVersion: v1
kind: Service
metadata:
  name: streaming-srv
spec:
  selector:
    app: streaming
  ports:
    - port: 3006
      targetPort: 3000
