apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db-depl
spec:
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: auth
            - name: POSTGRES_USER
              value:  postgresUser
            - name: POSTGRES_PASSWORD
              value: postgresSecret
              
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-srv
spec:
  selector:
    app: auth-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
