apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-db-depl
spec:
  selector:
    matchLabels:
      app: events-db
  template:
    metadata:
      labels:
        app: events-db
    spec:
      containers:
        - name: events-db
          image: mongo
          ports:
            - containerPort: 27017
         
---
apiVersion: v1
kind: Service
metadata:
  name: events-db-srv
spec:
  selector:
    app: events-db
  ports:
    - port: 27018
      targetPort: 27017
      protocol: TCP